### ISSUE TITLE
Rails 3 Support

### ISSUE THREAD

**Issue by abepetrillo** [modosc/cloudflare-rails#12]
Would you be interested in adding support for Rails 3? If so I can work on a PR. I have a rails 3 app which needs to keep track of IPs through a cloudflare proxy, so this seems like the ideal solution.

Let me know if your interested, I know Rails 3 is quite old at this point so understood if you want to keep the codebase clean.

**Comment by modosc** [comment]
thanks for the offer - at this point i'm not even supporting rails 4.2 in the main release so i don't think rails 3 support makes sense. feel free to fork and make it work - i'm happy to add a link in the readme.
