### ISSUE TITLE
Limiting traffic to just Cloudflare

### ISSUE THREAD

**Issue by philipithomas** [modosc/cloudflare-rails#145]
I'm interested in functionality in this gem to restrict traffic to Cloudflare. It should be optional and off by default. 

If I put cloudflare in front of my server, this gem helps decode the IP addresses of Cloudflare. And, it syncs the upstream servers of Cloudflare. 

But, if somebody finds out my server's address, they can bypass Cloudflare and connect to it directly, limiting the effectiveness of Cloudflare. 

If this gem has all the upstream IPs of Cloudflare, it should be possible to limit traffic to just Cloudflare to prevent people from bypassing security.

**Comment by pmor** [comment]
I've done this is the past by combining this gem with [rack-attack](https://github.com/rack/rack-attack).

I don't have code to share, but if memory serves, it was a blocklist that blocked any request that didn't match the Cloudflare IPs from this gem

**Comment by modosc** [comment]
i just added [documentation](https://github.com/modosc/cloudflare-rails?tab=readme-ov-file#blocking-non-cloudflare-traffic) on a possible approach using `Rack::Attack`. i'm not going to ship a rack middleware for this purpose in this gem - `Rack::Attack` already does this better than i could.

**Comment by philipithomas** [comment]
Thank you @modosc !
