### ISSUE TITLE
Possible issue with client IP in X-Forwarded-For when checking `#cloudflare?`

### ISSUE THREAD

**Issue by geoffharcourt** [modosc/cloudflare-rails#161]
We're looking at a new environment and while troubleshooting an issue, I think I found an issue in the Cloudflare request check. If this is actually a problem, it's not hole, it breaks in a way that's restrictive rather than permissive. However, I think it might fail for a not-uncommon setup.

A request from the client at 1.2.3.4 goes through Cloudflare to our ingress to our Puma server. We end up with:

`REMOTE_ADDR`: *trusted proxy*
`X_FORWARDED_FOR`: 1.2.3.4,*a-cloudflare-ip*

`#cloudflare?` checks if the request passed through Cloudflare by taking the remote address(es) and the IPs from `X-Forwarded-For`, chaining them together, and then taking elements from the left side until an untrusted IP address is encountered. However, if the client IP is on the left side of `X-Forwarded-For` (which seems allowable under the spec), we'll reject the request. Since appends happen to the right and we can only trust the right-most element of X-Forwarded-For, shouldn't we be evaluating from that direction and not from the left?

**Comment by mamhoff** [comment]
We tried this method on Heroku, and Heroku adds their own (private IP) load balancer as `REMOTE_ADDR`, and the user's IP as the first thing in `X-Forwarded-For`. I agree #162 is the right way to do this, may I asked why you closed it?

**Comment by geoffharcourt** [comment]
Hi! That was closed by accident. Thank you for flagging.
