### ISSUE TITLE
How to debug the gem not overriding `request.remote_ip` ?

### ISSUE THREAD

**Issue by marckohlbrugge** [modosc/cloudflare-rails#165]
For some reason `request.remote_ip` still shows the Cloudflare IP address for me.

1. I have installed the gem (confirmed by executing `CloudflareRails` in the production Rails console)
2. The cache store is configured (confirmed with `Rails.cache.write` and `Rails.cache.read` in production Rails console)
3. `request.remote_ip` is a Cloudflare IP address rather than my actual IP address (using simple action that displays the value which is `188.114.111.227`)

Any idea what might be going wrong? How can I further debug this?

**Comment by rameerez** [comment]
If you're using Kamal 2, you need to add `forward_headers: true` to your `proxy` section, like this:
```ruby
proxy:
  ssl: true
  host: example.com
  forward_headers: true
```

As per [Kamal's proxy docs](https://kamal-deploy.org/docs/configuration/proxy/): "By default, kamal-proxy will not forward the headers if the ssl option is set to true, and will forward them if it is set to false." – so you need to force it to `true` so the headers get passed to the Rails app.

**Comment by marckohlbrugge** [comment]
@rameerez I can confirm this fixed it for me 🙏
