### ISSUE TITLE
Advice on license

### ISSUE THREAD

**Issue by ewalk153** [modosc/cloudflare-rails#3]
I would like to use this software in our application. Can you clarify the license under which this gem is published? Anything such as Apache V2, MIT, BSD, Ruby public license would be appropriate for most users. Thanks.  If you add a license file to root of the project and add a line to the gemspec, a lot of automated tools would be able to scan the gem and publish the license. I'd be happy to do this for you through a PR with your permission.

**Comment by modosc** [comment]
thanks for pointing this out, i added the mit license and bumped up the version.
