### ISSUE TITLE
Dependency on 'rails' gem too broad

### ISSUE THREAD

**Issue by KieranP** [modosc/cloudflare-rails#34]
https://github.com/modosc/cloudflare-rails/blob/cd6365f6036ddf8417b342605b25f1fa0b33f4d4/cloudflare-rails.gemspec#L35

I have an app where I'm just using gems `railties`, `activesupport`, `actionpack`, and `actionmailer`. Your gem is depending on `rails`, which requires pulling in `actioncable`, `actionjob`, `activemodel`, `activerecord`, and `activestorage` which we don't use/need.

Since your gem only appends into ruby classes and one Rails class in `actionpack` (ActionDispatch), can you gem instead depend on `actionpack` rather than full Rails?

**Comment by StanBright** [comment]
That totally makes sense and should be an easy change. @KieranP I guess if you open a quick PR, it will be even faster to get the change through.

**Comment by modosc** [comment]
i'll look into this tomorrow. i think `activesupport` would be required as well for the `Rails.cache` call.

**Comment by modosc** [comment]
i have #35 opened and the specs pass but i don't have a test case for the minimal app you're describing. can you try it out via git and let me know?

**Comment by KieranP** [comment]
@modosc PR is working nicely 👍

**Comment by modosc** [comment]
just released this as v2.0.0 on rubygems, lmk if you have any issues!
