### ISSUE TITLE
Rails 5.1

### ISSUE THREAD

**Issue by semprini22** [modosc/cloudflare-rails#4]
Will there be a new release of this gem for Rails >= 5.1?

**Comment by modosc** [comment]
is it necessary? doesn't this pick it up?

https://github.com/modosc/cloudflare-rails/blob/master/cloudflare-rails.gemspec#L28

**Comment by semprini22** [comment]
It doesn't. ~> 5.0 is 5.0.0 <= version < 5.1

**Comment by semprini22** [comment]
I misunderstood the issue. You can ignore, sorry!
