### ISSUE TITLE
Chanes _may_ be required (Cloudflare IPs)

### ISSUE THREAD

**Issue by K1N5L4Y3R** [modosc/cloudflare-rails#42]
I received an email from Cloudflare, so just in case this is relevant to this gem and changes are needed I'm opening this issue

![image](https://user-images.githubusercontent.com/2091837/114110844-12a52680-989e-11eb-8d6f-6b89cf60b4c0.png)

Feel free to close this if this is not relevant.

**Comment by modosc** [comment]
thanks for the heads up! i think this should be fine - the default ttl for the cached copy of the ip list is 12 hours, so most users will just get the new version without having to do anything.
