### ISSUE TITLE
Cloudflare::Rails: Got exception: Permission denied

### ISSUE THREAD

**Issue by facundofarias** [modosc/cloudflare-rails#5]
Hello there,

This is just a question, not sure if it something that I've misconfigured, but the thing is.. every day since last week, I am watching this error event in my logs:

`error: Cloudflare::Rails: Got exception: Permission denied @ unlink_internal - /{MY_PROJECT_PATH}/tmp/cache/95A/060/cloudflare-rails%3Aips_v6 for type:ips_v6`

Any ideas? Seems to be related to the cache.. Shall I flush it?
Thanks

**Comment by modosc** [comment]
yeah, that’s a weird one, is this in development or production? is it possible that some sort of tmpwatch job is running and clearing out /tmp?

**Comment by facundofarias** [comment]
Is in production. Cannot reproduce it in development. I am not sure that a job would be running, at least is not one of my jobs. How can I control this exception?
Thanks!

**Comment by modosc** [comment]
i'm going to close this out - afaict it's not specific to this codebase but rather a rails configuration issue, sorry.
